### ISSUE TITLE
FATAL: ARP poisoning needs a non empty hosts list.

### ISSUE THREAD

**Issue by Silenthack3r** [Ettercap/ettercap#1257] opened 2024-06-11 17:56 UTC
i tried to change the value of user_tempaddr from 2 to 0 but it doesn't work
![Uploading Screenshot_2024-06-11_20_53_27.png…]()

**Comment by koeppea** [comment] 2024-06-11 21:17
I can't open the screenshot. Can you paste text-based?

**Comment by Silenthack3r** [comment] 2024-06-14 18:30
sudo ettercap -T -S -i eth0 -M arp:remote /192.168.1.1// /192.168.1.6//
[sudo] password for m1nt: 

ettercap 0.8.3.1 copyright 2001-2020 Ettercap Development Team

Listening on:
  eth0 -> 08:00:27:4B:99:A4
          10.0.2.15/255.255.255.0
          fe80::a00:27ff:fe4b:99a4/64

Ettercap might not work correctly. /proc/sys/net/ipv6/conf/eth0/use_tempaddr is not set to 0.
Privileges dropped to EUID 0 EGID 0...

  34 plugins
  42 protocol dissectors
  57 ports monitored
28230 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services
Lua: no scripts were specified, not starting up!

Scanning for merged targets (2 hosts)...

* |==================================================>| 100.00 %

0 hosts added to the hosts list...

FATAL: ARP poisoning needs a non empty hosts list.

**Comment by koeppea** [comment] 2024-06-14 21:57
OK this cannot work.
your victims are in 192.168.1.0/24 network, while your attacker machine running ettercap is in 10.0.2.0/24 network.
For doing a successful MITM based on ARP poisoning, the attacker **must be** located within the same subnet as the victim IPs.
The way you're trying this can not work by design, hence it's not a defect of Ettercap. Closing.

**Closed by koeppea** 2024-06-14 21:57 UTC
