### ISSUE TITLE
 Unable to generate HTTPS certificate in kali

### ISSUE THREAD

**Issue by nrz123** [Ettercap/ettercap#961] opened 2019-08-17 12:49 UTC
**my kali version:**
root@kali:~# uname -a
Linux kali 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-6kali1 (2019-07-22) x86_64 GNU/Linux

**now my ettercap version:**
root@kali:~# ettercap

ettercap 0.8.3 copyright 2001-2019 Ettercap Development Team

**the ettercap with kali is 0.8.2,and it can't generate the cert,then i uninstall the software and git the lastest source and make it,but now it can't support the https cert too**

**and this is my iptables when i start the sniff:**
root@kali:~# iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:telnets redir ports 59263
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:submissions redir ports 59264
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:pop3s redir ports 59265
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:nntps redir ports 59266
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:ldaps redir ports 59267
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:994 redir ports 59268
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:imaps redir ports 59269
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:http-alt redir ports 59270
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:https redir ports 59271
REDIRECT   tcp  --  anywhere             anywhere             tcp dpt:ftps redir ports 59272

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

this is the wireshake picture
![2019-08-17 19-32-27屏幕截图](https://user-images.githubusercontent.com/33199064/63211138-df8cad00-c125-11e9-8308-c9795aa2bde6.png)

and the target1 is 192.168.1.102 the target2 is 192.168.1.1,and my ip is 192.168.1.100
so in the picture we can see before the 119 line it is true,but the line 119 you can see the error,i don't know what is the question

**and then my openssl version:**

root@kali:~# openssl version
OpenSSL 1.1.1c  28 May 2019

you can see my conf
![2019-08-17 20-37-34屏幕截图](https://user-images.githubusercontent.com/33199064/63211812-e4a22a00-c12e-11e9-943c-e17644d4df4a.png)
![2019-08-17 20-38-38屏幕截图](https://user-images.githubusercontent.com/33199064/63211830-0d2a2400-c12f-11e9-87d8-6ea8075ab829.png)

i don't know what's wrong 
and my mother tongue is not English.There may be a lot of grammatical errors.

**Comment by nrz123** [comment] 2019-08-17 13:19
and i have tried uninstall the openssl or upgrade the kali or upgrade the ettercap.but it is also don't work.in kali,i have no idea make it work,whether in command line or in gnome.and the --certificate option can't make it work too
this is my command:
root@kali:~# ettercap -T -M ARP /192.168.1.102/ /192.168.1.1/ --certificate ./share/etter.ssl.crt
root@kali:~# ettercap -T -M ARP /192.168.1.102/ /192.168.1.1/ 
they are all invalid

**Comment by koeppea** [comment] 2019-08-18 09:10
So when I understand you correctly, you intercept HTTPS traffic with ettercap but then the SSL handshake fails. Correct?
Please read the newly created [Wiki page](https://github.com/Ettercap/ettercap/wiki/Providing-debug-information) to provide debug information required to troubleshoot the problem.

**Comment by nrz123** [comment] 2019-08-18 11:30
when i get your respones,i have tried reinstall the kali,4.19 amd64,but it is useless,and the i make source iwith debug,this is log
[ettercap-0.8.3_debug.log](https://github.com/Ettercap/ettercap/files/3512936/ettercap-0.8.3_debug.log)
i think start with line 671
and the target1 is 192.168.1.102 target2 is 192.168.1.1 my ip is 192.168.1.110
i can't realy understand the log,i hope it can be use

[error.tar.gz](https://github.com/Ettercap/ettercap/files/3512942/error.tar.gz)
and this is log and pcap

**Comment by nrz123** [comment] 2019-08-19 02:28
![QQ浏览器截屏未命名](https://user-images.githubusercontent.com/33199064/63235320-829b0f00-c26b-11e9-9ccf-f1dfd809ed33.png)
from the log i find this code,in the ec_socket.c line 105,in the log there is not error everytime,so is the loop number too small?
the error code is EALREADY,but i don't know what's mean

**Comment by koeppea** [comment] 2019-08-24 11:15
The retry loops are far enough and extending wouldn't also not solve the problem.
The problem lies in the ARP poison status of your router:
![image](https://user-images.githubusercontent.com/4201853/63636436-9b426500-c66f-11e9-8c4c-09114b2ea873.png)
Colored in green is the communication between the victim and the Ettercap.
Colored in blue is the communication between Ettercap and your Router.

It tries to establish the connection towards the actual destination with the source IP of your victim and the source MAC of the attacker. However it this connection attempt gets starved.

The reason is, that your router wasn't successfully poisoned and didn't override the ARP entry of the victim. So the SYN,ACK packets will be directed back to your victim directly w/o going over the attacker.

You can try to tweak ARP spoofing:
In the etter.conf play with the parameters `arp_poison_warm_up` and `arp_poison_delay`.
Alternatively, an not so aggressive but more intelligent method can be tried by setting the following parameters to 1: `arp_poison_smart` and if this also doesn't help `arp_poison_request`. Read the _etter.conf_ man page to understand what these parameters are responsible for.

But if your router's ARP cache is really that sticky, there's not much to do.
But this is not a problem or bug of Ettercap. Ettercap is working correctly.

**Comment by koeppea** [comment] 2019-08-24 11:25
Ah wait a second. The outbound connection that starves out is made from Ettercap's source IP.
So it might really be some kind of IPS functionality of your router. So making ARP poison more silent may help here. I assume when Ettercap isn't running, the attacker machine has no issues with Internet connectivity?

**Comment by nrz123** [comment] 2019-08-25 13:53
i have tried the smart and the request,but it invalid,and i tried the more set
but if ettercap use the attacker ip and attacker mac to get the connect with dst,like a proxy,then it just only need poison the victim.is there this option in ettercap?

**Comment by nrz123** [comment] 2019-08-25 14:57
but infact when i found the other tcp packets with the wireshark,i have found many packet that the dst ip is victim and the dst mac is attacker from the router,is it means router is successfully poisoned,

**Comment by nrz123** [comment] 2019-08-25 15:04
maybe i can give my new log
[error.zip](https://github.com/Ettercap/ettercap/files/3538254/error.zip)

**Comment by nrz123** [comment] 2019-08-25 15:36
maybe i can give you the new log
[error.zip](https://github.com/Ettercap/ettercap/files/3538274/error.zip)
because i find many packet that dst ip is victim and dst mac is attcaker and the src is router,i think it means router is successfully poisoned
route ip is 192.168.1.1 mac is 28:2c:b2:4a:31:ec
attacker ip is 192.168.1.107 mac is f8:34:41:bb:96:30
victim ip is 192.168.1.105 mac is c4:9f:4c:d1:e0:6c
and the log show some different whit the old

**Comment by koeppea** [comment] 2019-08-26 17:41
Yes you're right. This debug package contains a better example.
I can see now that the attacker can communicate with the outside world, but the attacker aborts the TLS handshake with the victim.
I've to try to reproduce..... getting back as soon I've any news.

**Comment by nrz123** [comment] 2019-09-09 18:45
when i check the code,i find question in ec_sslwrap.c line 548,SSL_accept failed, and SSL_get_error return 1,when i call the ERR_error_string,the function give the string is "SSL routines:tls_post_process_client_hello:no shared cipher"

**Comment by koeppea** [comment] 2019-09-10 20:13
Thanks for the checking. However I don't think that this is related to shared cipher suite, since the server picks a suite in the Server Hello. The handshake failure happens later.
What wonders me a bit, is that the first Client Hello from the Victim doesn't contain a Session ID but the spawned Client Hello from the Attacker does have a Session ID.

**Comment by koeppea** [comment] 2019-10-02 17:56
Can you compile the pull-request #971 and try if this improves something?
First tests on my side look promising.

**Comment by koeppea** [comment] 2019-11-21 17:31
I think I've now fixed the SSL problem you're facing.
Fix is in PR #971 and contains also some other SSL intercept improvements, tough which may not be relevan for your issue.
Can you please test if PR #971 fixes the issue you're experiencing?

**Comment by koeppea** [comment] 2019-11-27 23:09
Closing since fixing PR #971 has been merged

**Closed by koeppea** 2019-11-27 23:09 UTC
Labels: fix proposed
