### ISSUE TITLE
Sudo Ettercap Doesn't Load

### ISSUE THREAD

**Issue by oYes000123** [Ettercap/ettercap#908] opened 2018-09-09 22:22 UTC
I've followed all of the steps on youtube to set up my sudo ettercap on my Mac. After I finally was able to open it I found out that it doesn't work. I can scan and use basic items on the interface but they don't actually do anything. If I try to type anything ettercap loads forever until I end up quitting it. In the terminal it says 'Error Opening File (directory)'.  Does anybody know how to solve this?

**Comment by sgeto** [comment] 2018-09-10 06:02
You have to be much more specific if you're expecting to get help.

You could fill out this form for instance (borrowed from scapy):
```
#### Brief description

< describe the main issue in one sentence >

< if possible, describe what components/protocols could be affected by the issue (e.g. IPv6, it is likely this also affects XXX) >

#### Environment

- ettercap version: < ettercap version and/or commit-hash >
- Operating System: < e.g. Minix 3.4 >

< if needed - further information to get a picture of your setup (e.g. a sketch of your network setup) >

#### How to reproduce

< step-by-step explanation or a short script, may reference section 'Related resources' >

#### Actual result

< dump results that outline the issue, please format your code >

#### Expected result

< describe the expected result and outline the difference to the actual one, could also be a screenshot (e.g. Wireshark) >

#### Related resources

<traces/sample/pcaps (stripped to the relevant frames), related standards, RFCs or other resources > 
```

**Comment by koeppea** [comment] 2018-09-15 21:31
@oYes000123 when you followed the steps on Youtube, you'd have build ettercap in Debug mode.
Can you pls provide the content of **ettercap-0.8.2_debug.log**?
It's created in the directory where ettercap has been executed (maybe also in root's home).

Also for graphical issues, screenshots really help. Thanks.

**Comment by koeppea** [comment] 2018-10-21 08:17
@oYes000123 any update?

**Comment by koeppea** [comment] 2018-10-24 07:11
Closing as a duplicate of #911

**Closed by koeppea** 2018-10-24 07:11 UTC
