### ISSUE TITLE
ettercap crash's (Cannot open etter.finger.mac) Permission Error

### ISSUE THREAD

**Issue by beastie101** [Ettercap/ettercap#867] opened 2018-02-13 08:42 UTC
I installed ettercap into $HOME/.local and I changed the CMakeLists.txt's ${INSTALL_PREFIX} paths to point my $HOME/.local as my system root. (eg:- System configuration directory was pointing /etc I changed it to $HOME/.local/etc).

When ettercap opens 'etter.finger.mac' (it is done by 'open_data()' function defined in src/ec_file.c) it returns NULL file descriptor. I do not know why is this happening and the file still exists there.

I wrote another C code to simulate this. But it works fine no permission errors as root.
```
#include <stdio.h>

int main()
{
	FILE *fd;
	fd = fopen("./share/etter.finger.mac", "r");
	printf("%d\n", fd);
	close(fd);
	return 0;
}
```

Can anyone tell me a way of fixing this?

I already disabled SElinux and It did not work. Ran as root.

**Comment by koeppea** [comment] 2018-02-13 19:47
Can you please provide the output and the debug log file?

**Comment by beastie101** [comment] 2018-02-14 04:51
What debug? you mean runtime debug and output?

**Comment by beastie101** [comment] 2018-02-14 06:26
==============================================================

-> ${prefix}        /home/minol/.local
-> ${exec_prefix}   /home/minol/.local
-> ${bindir}        /home/minol/.local/bin
-> ${libdir}        /home/minol/.local/lib
-> ${sysconfdir}    /home/minol/.local/etc
-> ${datadir}       /home/minol/.local/share

-> ettercap 0.8.2

-> compiled with gcc 4.8 (/usr/bin/cc)
-> glibc version 2.17
-> libpcap version 1.5.3
-> libnet version 1.1.6
-> libz version 1.2.7
-> libpcre version 8.32 2012-11-30
-> lib     OpenSSL 1.0.2k-fips  26 Jan 2017
-> headers OpenSSL 1.0.2k  26 Jan 2017


DEVICE OPENED FOR ettercap DEBUGGING

[NR_THREAD]	main -- here we go !!
[NR_THREAD]	ec_thread_register -- [140703836625472] init
[     init]	signal_handler activated
[     init]	parse_options -- [0] [/home/minol/.local/bin/ettercap]
[     init]	parse_options -- [1] [-G]
[     init]	select_gtk_interface
[     init]	GTK -> gtk+ 2.24.31

[     init]	parse_options: options parsed
[     init]	compile_target TARGET: //
[     init]	MAC  : []
[     init]	IP   : []
[     init]	PORT : []
[     init]	compile_target TARGET: //
[     init]	MAC  : []
[     init]	IP   : []
[     init]	PORT : []
[     init]	parse_options: targets parsed
[     init]	set_unified_sniff
[     init]	parse_options: options combination looks good
[     init]	init_structures
[     init]	load_conf
[     init]	get_full_path -- [etc] /home/minol/.local/etc/ettercap/etter.conf
[     init]	open_data (/home/minol/.local/etc/ettercap/etter.conf)
[     init]	load_conf: SECTION: privs
[     init]	load_conf: 	ENTRY: ec_uid  65534
[     init]	load_conf: 	ENTRY: ec_gid  65534
[     init]	load_conf: SECTION: mitm
[     init]	load_conf: 	ENTRY: arp_storm_delay  10
[     init]	load_conf: 	ENTRY: arp_poison_smart  0
[     init]	load_conf: 	ENTRY: arp_poison_warm_up  1
[     init]	load_conf: 	ENTRY: arp_poison_delay  10
[     init]	load_conf: 	ENTRY: arp_poison_icmp  1
[     init]	load_conf: 	ENTRY: arp_poison_reply  1
[     init]	load_conf: 	ENTRY: arp_poison_request  0
[     init]	load_conf: 	ENTRY: arp_poison_equal_mac  1
[     init]	load_conf: 	ENTRY: dhcp_lease_time  1800
[     init]	load_conf: 	ENTRY: port_steal_delay  10
[     init]	load_conf: 	ENTRY: port_steal_send_delay  2000
[     init]	load_conf: SECTION: connections
[     init]	load_conf: 	ENTRY: connection_timeout  300
[     init]	load_conf: 	ENTRY: connection_idle  5
[     init]	load_conf: 	ENTRY: connection_buffer  10000
[     init]	load_conf: 	ENTRY: connect_timeout  5
[     init]	load_conf: SECTION: stats
[     init]	load_conf: 	ENTRY: sampling_rate  50
[     init]	load_conf: SECTION: misc
[     init]	load_conf: 	ENTRY: close_on_eof  1
[     init]	load_conf: 	ENTRY: store_profiles  1
[     init]	load_conf: 	ENTRY: aggressive_dissectors  1
[     init]	load_conf: 	ENTRY: skip_forwarded_pcks  1
[     init]	load_conf: 	ENTRY: checksum_check  0
[     init]	load_conf: 	ENTRY: submit_fingerprint  0
[     init]	load_conf: 	ENTRY: checksum_warning  0
[     init]	load_conf: 	ENTRY: sniffing_at_startup  1
[     init]	load_conf: 	ENTRY: geoip_support_enable  1
[     init]	load_conf: SECTION: dissectors
[     init]	dissect_modify: ftp replaced to 21
[     init]	dissect_modify: ssh replaced to 22
[     init]	dissect_modify: telnet replaced to 23
[     init]	dissect_modify: smtp replaced to 25
[     init]	dissect_modify: dns replaced to 53
[     init]	dissect_modify: dhcp replaced to 67
[     init]	dissect_modify: http replaced to 80
[     init]	dissect_modify: ospf replaced to 89
[     init]	dissect_modify: pop3 replaced to 110
[     init]	dissect_modify: vrrp replaced to 112
[     init]	dissect_modify: nntp replaced to 119
[     init]	dissect_modify: smb replaced to 139
[     init]	dissect_modify: smb added on 445
[     init]	dissect_modify: imap replaced to 143
[     init]	dissect_modify: imap added on 220
[     init]	dissect_modify: snmp replaced to 161
[     init]	dissect_modify: bgp replaced to 179
[     init]	dissect_modify: ldap replaced to 389
[     init]	sslw_dissect_move: https [443]
[     init]	dissect_modify: https replaced to 443
[     init]	sslw_dissect_move: ssmtp [465]
[     init]	dissect_modify: ssmtp replaced to 465
[     init]	dissect_modify: rlogin replaced to 512
[     init]	dissect_modify: rlogin added on 513
[     init]	dissect_modify: rip replaced to 520
[     init]	sslw_dissect_move: nntps [563]
[     init]	dissect_modify: nntps replaced to 563
[     init]	sslw_dissect_move: ldaps [636]
[     init]	dissect_modify: ldaps replaced to 636
[     init]	sslw_dissect_move: telnets [992]
[     init]	dissect_modify: telnets replaced to 992
[     init]	sslw_dissect_move: imaps [993]
[     init]	dissect_modify: imaps replaced to 993
[     init]	sslw_dissect_move: ircs [994]
[     init]	dissect_modify: ircs replaced to 994
[     init]	sslw_dissect_move: pop3s [995]
[     init]	dissect_modify: pop3s replaced to 995
[     init]	dissect_modify: socks replaced to 1080
[     init]	dissect_modify: radius replaced to 1645
[     init]	dissect_modify: radius added on 1646
[     init]	dissect_modify: msn replaced to 1863
[     init]	dissect_modify: cvs replaced to 2401
[     init]	dissect_modify: mysql replaced to 3306
[     init]	dissect_modify: icq replaced to 5190
[     init]	dissect_modify: ymsg replaced to 5050
[     init]	dissect_modify: mdns replaced to 5353
[     init]	dissect_modify: vnc replaced to 5900
[     init]	dissect_modify: vnc added on 5901
[     init]	dissect_modify: vnc added on 5902
[     init]	dissect_modify: vnc added on 5903
[     init]	dissect_modify: x11 replaced to 6000
[     init]	dissect_modify: x11 added on 6001
[     init]	dissect_modify: x11 added on 6002
[     init]	dissect_modify: x11 added on 6003
[     init]	dissect_modify: irc replaced to 6666
[     init]	dissect_modify: irc added on 6667
[     init]	dissect_modify: irc added on 6668
[     init]	dissect_modify: irc added on 6669
[     init]	dissect_modify: gg replaced to 8074
[     init]	sslw_dissect_move: proxy [8080]
[     init]	dissect_modify: proxy replaced to 8080
[     init]	dissect_modify: rcon replaced to 27015
[     init]	dissect_modify: rcon added on 27960
[     init]	dissect_modify: ppp replaced to 34827
[     init]	dissect_modify: TN3270 replaced to 23
[     init]	dissect_modify: TN3270 added on 992
[     init]	load_conf: SECTION: curses
[     init]	load_conf: 	ENTRY: color_bg  0
[     init]	load_conf: 	ENTRY: color_fg  7
[     init]	load_conf: 	ENTRY: color_join1  2
[     init]	load_conf: 	ENTRY: color_join2  4
[     init]	load_conf: 	ENTRY: color_border  7
[     init]	load_conf: 	ENTRY: color_title  3
[     init]	load_conf: 	ENTRY: color_focus  6
[     init]	load_conf: 	ENTRY: color_menu_bg  4
[     init]	load_conf: 	ENTRY: color_menu_fg  6
[     init]	load_conf: 	ENTRY: color_window_bg  4
[     init]	load_conf: 	ENTRY: color_window_fg  7
[     init]	load_conf: 	ENTRY: color_selection_bg  6
[     init]	load_conf: 	ENTRY: color_selection_fg  6
[     init]	load_conf: 	ENTRY: color_error_bg  1
[     init]	load_conf: 	ENTRY: color_error_fg  3
[     init]	load_conf: 	ENTRY: color_error_border  3
[     init]	load_conf: SECTION: strings
[     init]	load_conf: 	ENTRY: utf8_encoding  [ISO-8859-1]
[     init]	load_conf: 	ENTRY: remote_browser  [xdg-open http://%host%url]
[     init]	load_conf: 	ENTRY: geoip_data_file  [/usr/local/share/GeoIP/GeoIP.dat]
[     init]	load_conf: 	ENTRY: geoip_data_file_v6  [/usr/local/share/GeoIP/GeoIPv6.dat]
[     init]	capture_getifs
[     init]	capture_getifs: [usbmon1] USB bus number 1
[     init]	capture_getifs: [enp2s0] enp2s0
[     init]	capture_getifs: [usbmon2] USB bus number 2
[     init]	capture_getifs: [usbmon3] USB bus number 3
[     init]	capture_getifs: [lo] Local Loopback
[     init]	ui_init
[     init]	gtk_init
[     init]	gtkui_conf_read: /root/.config/ettercap_gtk
[     init]	gtkui_conf_set: name=window_top value=172
[     init]	gtkui_conf_set: name=window_left value=89
[     init]	gtkui_conf_set: name=window_height value=497
[     init]	gtkui_conf_set: name=window_width value=817
[     init]	gtkui_setup
[     init]	gtkui_conf_get: name=window_width
[     init]	gtkui_conf_get: name=window_height
[     init]	gtkui_conf_get: name=window_left
[     init]	gtkui_conf_get: name=window_top
[     init]	gtk_setup: end
[     init]	gtk_unified_sniff
[     init]	init_network
[     init]	source_init enp2s0
[     init]	requested snaplen for enp2s0: 65535, assigned snaplen: 65535
[     init]	get_iface_mtu: 1500
[     init]	l3_init
[     init]	disable_ip_forward: old value = 0
[     init]	disable_interface_offload: Disabling offload on enp2s0
[     init]	ssl_wrap_init: no redirect script
[     init]	drop_privs: seteuid(65534) setegid(65534)
[     init]	privs: UID: 0 65534  GID: 0 65534
[     init]	plugin_loadall
[     init]	plugin_loadall: no plugin in /home/minol/.local/lib/ettercap searching locally...
[     init]	plugin_loadall: -1 found
[     init]	get_full_path -- [share] /home/minol/.local/share/ettercap/etter.finger.mac
[     init]	open_data (/home/minol/.local/share/ettercap/etter.finger.mac)
[     init]	get_local_path -- ./share/etter.finger.mac
[     init]	open_data dropping to ./share/etter.finger.mac
[     init]	ERROR : 13, Permission denied
[/home/minol/Downloads/ettercap/src/ec_manuf.c:manuf_init:128] Cannot open etter.finger.mac 

[     init]	ui_cleanup
[     init]	clean_exit: -13
[     init]	mitm_stop
[     init]	stop_unified_sniff
[     init]	ec_thread_kill_all -- caller 140703836625472 [init]
[     init]	ATEXIT: plugin_unload_all
[     init]	ATEXIT: regain_privs
[     init]	ATEXIT: close_network
[     init]	ATEXIT: send_closed


DEVICE CLOSED FOR DEBUGGING

**Comment by beastie101** [comment] 2018-02-14 06:27
seems dropping privileges

**Comment by koeppea** [comment] 2018-02-15 16:26
Correct. By default it drops to nobody. So either you adjust the permissions of the whole path or you set ec_uid and ec_gid to the ids of your user/group. Or 0 for remaining on root.

**Comment by koeppea** [comment] 2018-02-15 22:32
Since pretty much probable this is the cause of your issue, I close this issue.
If you think it's not fixed following my suggestion, feel free to reopen and continue.

**Closed by koeppea** 2018-02-15 22:32 UTC

**Comment by beastie101** [comment] 2018-02-16 06:45
Thanks for the response. For the time being I can handle the error after your instructions to examine debug log file. But I want to install ettercap inside $HOME/.local directory so that ettercap's libraries would not conflict with the ones already available in the system. I would like for this conflict to be resolved on ettercap itself.

**Comment by koeppea** [comment] 2018-02-16 08:25
There is no conflict. It’s just due to the permission drop to nobody by default. It’s security wise good practice to release application permissions when they’re not needed anymore.

You just set your path permissions or configure other uid in **etter.conf** permanently.

**Comment by beastie101** [comment] 2018-02-16 08:30
:+1:
