### ISSUE TITLE
An error occurred with the message too long in the ettercap 0.8.3.1 

### ISSUE THREAD

**Issue by aBenup** [Ettercap/ettercap#1178] opened 2022-04-13 08:42 UTC
I tamper with the data using bridge mode, but there is always an error that the message is too long. I know the old version has this bug.
In addition, when the data is tampered with by ettercap for more than one minute, if the tampering is stopped, TCP retransmission will occur, resulting in the interruption of communication between the client and the server. I use Wireshark to capture packets and find that the seq of the packets that generated TCP retransmission was incorrect.

**Comment by koeppea** [comment] 2022-04-14 04:48
Can you please share a PCAP that is demonstrating this?

**Comment by aBenup** [comment] 2022-04-14 06:28
I only have picture now, I will test it later. If this problem occurs again, I will send you the PCAP file.
![ettercap_bug](https://user-images.githubusercontent.com/89883419/163326653-91dec6b5-00f7-4b79-9765-6b4ea5c7b660.jpg)

**Comment by aBenup** [comment] 2022-04-14 13:17
Unfortunately, I failed to reproduce the bug: the message too long. But I have another question. I used ettercap to tamper with the data sent by the client to the receiving end, and the receiving end can receive the tampered data. However, when ettercap stops tampering, TCP retransmission occurred, so that the connection between the client and the receiving end was disconnected. This is Wireshark's capture file，You can use tcp.port == 8888 for filtering. Thank you very much.
[wireshark_pcap.zip](https://github.com/Ettercap/ettercap/files/8489437/wireshark_pcap.zip)

**Comment by koeppea** [comment] 2022-04-14 17:20
This is natural. When you insert or remove data from a TCP stream, the sequence and acknowledgement numbers between client and server get out of sync by design.

Ettercap holds both together and translates the out of sync numbers. As soon as you take Ettercap out, client and server are faced with the out of sync TCP connection with no way to recover.

There is nothing that could fix that other than to do the exact reverse thing (+-) before Ettercap leaves the connection alone.

This is not a defect of Ettercap rather than by design.

**Comment by aBenup** [comment] 2022-04-15 01:01
Awesome. I see. Thank you sincerely.

**Comment by koeppea** [comment] 2022-04-15 01:03
Closing the issue then. Please open a new one, if you can reproduce the message too long message consistently.

**Closed by koeppea** 2022-04-15 01:03 UTC
