### ISSUE TITLE
SSLStrip: plugin load failed: Could not compile find_cookie regex: 11

### ISSUE THREAD

**Issue by gold604** [Ettercap/ettercap#865] opened 2018-02-06 16:26 UTC
Hi, when I was trying to start sslstrip plugin i got an error. I have tried to install ettercap from git, but it still doesn't work. 

Ettercap v.: 0.8.2
SSLStrip v.: 1.2
SSLStrip log:
```
Activating sslstrip plugin...
SSLStrip plugin: bind 80 on 59273
SSLStrip: plugin load failed: Could not compile find_cookie regex: 11
```

**Comment by koeppea** [comment] 2018-02-07 14:47
Have you built in debug mode? If yes, could you please provide the ettercap_log file?

**Comment by gold604** [comment] 2018-02-07 14:59
No, I haven't. How can I do that? I have used ettercap GUI by the way.

**Comment by sgeto** [comment] 2018-02-10 01:24
> How can I do that?

change the cmake build type to debug:
`cmake -DCMAKE_BUILD_TYPE=Debug ...`

Can you list the steps to reproduce this problem?
And some more information about your setup and OS would be nice too.

**Comment by sgeto** [comment] 2018-02-10 01:32
Also:
ettercap's sslstrip plugin is separate from SSLStrip v.: 1.2 by moxie0.
You know that, right? (As in: Don't use them alongside each other)

**Comment by gold604** [comment] 2018-02-10 13:04
I use Kali Linux. I am connected to the network via Wi-Fi(Intel). CPU: Intel Core i5-2520M @ 2.50GHz. /proc/version: Linux version 4.14.0-kali3-amd64 (devel@kali.org) (gcc version 7.2.0 (Debian 7.2.0-19)) #1 SMP Debian 4.14.13-1kali1 (2018-01-25). 

Steps to reproduce this problem:

1. Open terminal and type ettercap -G
2. Sniff > Unified sniffing... then select your current network interface(wlan0 for me) and click Ok
3. Plugins > Manage the plugins then find sslstrip in the list and double click it
4. Done.

[Here is ettercap-0.8.2_debug.log](https://pastebin.com/RNiWDpnR)

**Comment by gold604** [comment] 2018-02-10 14:08
I have updated all packages before trying it. And i didn't run SSLStrip from moxie0 in the background.

**Comment by sgeto** [comment] 2018-02-10 17:12
have you ran `apt update && apt upgrade` before building?

**Comment by gold604** [comment] 2018-02-10 17:18
@sgeto Yes I have.

**Comment by sgeto** [comment] 2018-02-10 17:35
I just tried it on my older Kali box (4.3.0-kali1-amd64 #1 SMP Debian 4.3.3-5kali4) and it work normally.
This could be an issue with mismatching parenthesis/braces in regex, but then it would break on other operating systems as well.
Maybe a problem on Kali?

Can you compile again without PCRE and run again?
`cmake -DCMAKE_BUILD_TYPE=Debug -DHAVE_PCRE=0 ..`

**Comment by gold604** [comment] 2018-02-10 17:42
@sgeto Even without PCRE it doesn't work.

**Comment by sgeto** [comment] 2018-02-10 18:15
It was just a wild guess...

Can you post a few more files?
First configure with:
cmake -DCMAKE_BUILD_TYPE=Debug  -DCMAKE_VERBOSE_MAKEFILE=ON ..

1. `CmakeCache.txt` (in your build folder)
2. `CmakeFiles/CmakeOutput.log` (in your build folder)
3. The _entire_ output of the `make` command (run `make 2>&1 | tee make.txt` instead of just `make`)

**Comment by koeppea** [comment] 2018-02-10 20:36
What are the values in your *etter.conf* for the following parameters:
```
egrep -v '^( *#|$)' /etc/ettercap/etter.conf | egrep 'ec_[ug]id|redir'
```
I'd also be interessted in the status of **iptables** before and after the activation of _sslstrip_:
```
iptables -nL -tnat
```

**Comment by gold604** [comment] 2018-02-10 20:49
1.  
```ec_uid = 65534                # nobody is the default
ec_gid = 65534                # nobody is the default
   redir_command_on = "iptables -t nat -A PREROUTING -i %iface -p tcp --dport %port -j REDIRECT --to-port %rport"
   redir_command_off = "iptables -t nat -D PREROUTING -i %iface -p tcp --dport %port -j REDIRECT --to-port %rport"
````
2.1(before - ettercap isnt openned)
```Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
```
2.2(after)
```Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:992 redir ports 59263
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:465 redir ports 59264
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:995 redir ports 59265
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:563 redir ports 59266
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:636 redir ports 59267
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:994 redir ports 59268
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:993 redir ports 59269
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8080 redir ports 59270
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 59271
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:990 redir ports 59272

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
```

**Comment by koeppea** [comment] 2018-02-10 20:52
can you pls try with settinge both **ec_uid** and **ec_gid** to _0_?

**Comment by gold604** [comment] 2018-02-10 20:56
@koeppea Still same error.

**Comment by koeppea** [comment] 2018-02-10 21:15
Could you please try my branch fix-865:
```
cd $where_the_ettercap_directory_resides
git clone https://github.com/koeppea/ettercap ettercap.koeppea
cd ettercap.koeppea
git checkout fix-865
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug ..
make
sudo make install
```
Then try to reproduce the issue.

**Comment by gold604** [comment] 2018-02-10 22:01
@koeppea Same error, again.

**Comment by koeppea** [comment] 2018-02-10 22:36
Can you please try again:
```
git pull
make
sudo make install
```

**Comment by gold604** [comment] 2018-02-10 22:39
@koeppea inside build directory, right?

**Comment by gold604** [comment] 2018-02-10 23:08
Plugin activation finally works, but there is another problem. After ARP spoofing(victim+router) victim can't access HTTPS sites: `NET::ERR_CERT_INVALID`. I am sure it didnt do before. SSLStrip plugin wasn't activated by the way.

**Comment by koeppea** [comment] 2018-02-10 23:52
yes

**Comment by sgeto** [comment] 2018-02-11 02:05
@koeppea Can you explain what was wrong?

**Comment by koeppea** [comment] 2018-02-11 07:39
@sgeto
I don't know why because he uses the same version of libpcre than me and I cannot reproduce myself. But the error code 11 means "Invalid range end". 
In Regex a range is e.g. `[a-z]`. 
If you however use this as simple character class including a **-**, this can lead to this issue: if you wanna match e.g. a **-**, **a** and a **1** you could use `[a-1]` but this leads to the same error since it's interpreted as a range but the range end is invalid. In some cases, even escaping doesn't work but puting the **-** at the end helps since then Regex doesn't try to expand it as a range.

If this fixes the issue @gold604 has, I'll make the error message a bit more descriptive when opening a PR.

However @gold604, I remember having read something that this particular issue doesn't appear anymore, but don't find it here???? 
Could you please confirm whether or not, my branch fixes this particular issue?

Subsequent discussion can of course go on (e.g. SSL errors etc). But primarily I'd like to focus on the issue reported here.

**Comment by gold604** [comment] 2018-02-11 16:13
Hi, yes I have deleted my last post. Plugin activation works very well, but there is another problem: when I uncomment `redir_commmand_on` and `redir_commmand_off` victim is getting SSL errors when acessing HTTPS sites. This problem is in main branch as well.

**Comment by koeppea** [comment] 2018-02-11 21:04
@gold604 thanks for confirming. Lets get this finished first before getting to the redir command issue:
I've just encountered that the version you've tested has a warning in _sslstrip.c_.
Can you please retry my latest version of my branch:
In the build directory of my branch `ettercap.koeppea/build`:
```
git reset --hard 63570be7
git pull
make
sudo make install
```
Thanks.

**Comment by gold604** [comment] 2018-02-11 21:13
@koeppea works fine

**Comment by koeppea** [comment] 2018-02-12 08:12
Fixed by pull-request #866.

**Closed by koeppea** 2018-02-12 08:12 UTC

**Comment by koeppea** [comment] 2018-02-12 08:19
@gold604 So about the SSL issue:
**sslstrip**, requires the *redir_command_{on,off}* being enabled.
However, this motivates ettercap to automatically install the "standard" redirection rules as well (see the **iptables** output above).
That means, that not only traffic on port 80 is being redirected to ettercap for interception, but also HTTPS for example. So this SSL traffic is being intercepted by ettercap and by default ettercap uses its own self-signed certificate. Therefore users whose traffic you've attracted using a MITM technique are automatically intercepted.

This behaviour is admited not optimal and I have already on my plate to improve that making this more selective. But if you wish to change this behaviour, you can modify the iptables rules after ettercap has started so that only the traffic is being redirected for interception that you intend.

Does that address your subsequent issue?

**Comment by gold604** [comment] 2018-02-12 12:43
Yes, thank you very much.
