### ISSUE TITLE
Target down

### ISSUE THREAD

**Issue by luismartinsez** [Ettercap/ettercap#967] opened 2019-09-10 08:11 UTC
Using ettercap or etterfilter, is it possible to temporarily disable the network interface of targets, during ARP poisoning? or is there a way to create an impression that target is down or out of the network? Basically, none should be able to communicate with target, during attack.

Any ideas welcome :-)

**Comment by koeppea** [comment] 2019-09-10 20:18
I think that's the purpose of the _isolate_ plugin.

**Comment by luismartinsez** [comment] 2019-09-11 11:29
That's great! Yes, isolate plugin can do the job.

However, it's not working when I fired the following command.

sudo ettercap -Tq -i enp0s25 -P isolate /192.168.0.67/ //

I flushed ARP using sudo ip -s -s neigh flush all, but in vain. There was a note that it will take 5 minutes or more to work so waited for at least an hour without any luck.

Could you try at your end please?

**Comment by koeppea** [comment] 2019-10-20 09:42
I'm not aware of a 5 minute duration limit. I just checked the source code but also don't find a hint that it stops.

The output you show throw some warnings but nothing that are related to the operation of the plugin:
```
Cannot change large-receive-offload
```
Apparently `ethtool` isn't installed therefore ettercap cannot disable TSO. But this doesn't relate to ARP at all.

```
SSL dissection needs a valid 'redir_command_on' script in the etter.conf file
```
Ettercap doesn't run with privileges rights. This is only required if you want to use SSL interception. Agian nothing related to the plugin.

```
mdns_spoof: etter.mdns:52 Invalid IPv4 or IPv6 address
mdns_spoof: etter.mdns:54 Invalid IPv4 or IPv6 address
mdns_spoof: etter.mdns:61 Invalid IPv4 or IPv6 address
dns_spoof: etter.dns:71 Invalid IPv4 or IPv6 address
dns_spoof: etter.dns:78 Invalid IPv4 or IPv6 address
dns_spoof: etter.dns:81 Invalid IPv4 or IPv6 address
dns_spoof: etter.dns:90 Invalid IPv4 or IPv6 address
dns_spoof: etter.dns:99 Invalid IPv4 or IPv6 address
dns_spoof: etter.dns:112 Invalid IPv4 or IPv6 address
```
This is because your version of ettercap has been compiled w/o support for IPv6, hence it cannot parse the examples in the config files for *dns_spoof* and *mdns_spoof* plugin. I just have raised another pull request to address these warnings. But here also, nothing related to the isolate plugin.

So do you actually have a problem with the plugin?

**Comment by luismartinsez** [comment] 2019-10-20 10:25
Thanks for looking into this matter Alexander, very much appreciated. My further tests proved that the plugin works for personal computers on LAN. However, it doesn’t want to isolate PLC’s out of the network. PLC has an IP address.

We dropped this idea, so it can be closed.

Would appreciate if you can propose a workaround to tackle ‘pause’ feature in etterfilter (#956)

**Comment by koeppea** [comment] 2019-10-20 11:47
OK well isolate plugin works of course only within the same LAN (broadcast domain).
So it's by design that it is ineffective for hosts outside the broadcast domain.
Closing.
P.S. it's still on my plate however currently have to focus on fixing SSL interception when TLS1.3 is involved which is more important as SSL interception a core feature.

**Closed by koeppea** 2019-10-20 11:47 UTC

**Comment by luismartinsez** [comment] 2019-10-20 12:42
Thank you for the explanation.

Pause - noted. Thanks
