### ISSUE TITLE
"make" command does not work for source compilation

### ISSUE THREAD

**Issue by Schnuggs** [Ettercap/ettercap#883] opened 2018-03-14 20:36 UTC
Trying to install Ettercap on a Debian machine. Installed all the required dependencies using `apt-get install debhelper bison check cmake flex ghostscript libbsd-dev libcurl4-openssl-dev libgtk2.0-dev \
 libltdl-dev libluajit-5.1-dev libncurses5-dev libnet1-dev libpcap-dev libpcre3-dev libssl-dev libgtk-3-dev`. I'm able to unpack the `ettercap-0.8.2.tar.gz` file, create a `build` directory within it, and use `cmake ../`. After that, using the `make` command gives me this error at about 17% build completion: 

`/home/attacker/Downloads/ettercap-0.8.2/src/ec_sslwrap.c: In function 'sslw_create_selfsigned':
/home/attacker/Downloads/ettercap-0.8.2/src/ec_sslwrap.c:978:13: error: dereferencing pointer to incomplete type
'X509_EXTENSION {aka struct X509_extension_st}'
ext->value->data[7] = 0xe7;`

`src/CMakeFiles/lib_ettercap.dir/build.make:1142: recipe for target` `'src/CMakeFiles/lib_ettercap.dir/ec_sslwrap.c.o' failed`
`make[2]: *** [src/CMakeFiles/lib_ettercap.dir/ec_sslwrap.c.o] Error 1`
`CMakeFiles/Makefile2:249: recipe for target 'src/CMakeFiles/lib_ettercap.dir/all' failed`
`make[1]: *** [src/CMakeFiles/lib_ettercap.dir/all] Error 2`
`Makefile:127: recipe for target 'all' failed`
`make: *** [all] Error 2`

[Here](https://i.stack.imgur.com/kU5YV.png) is an image of the error, might help classify/solve it.

I've been trying to troubleshoot it for hours, and I've checked my dependency installs a hundred times, but I just have no idea how to fix this. Can someone give me some pointers? Thanks.

**Comment by koeppea** [comment] 2018-03-15 06:44
OpenSSL evolved quite a bit in the meantime.

Throw away the unpacked source from the tarball.
Get the latest source from Github (‘git clone https://github.com/Ettercap/ettercap’) and try again to build following the same procedure.

**Comment by koeppea** [comment] 2018-03-15 13:23
If this doesn’t fix the build issue feel free to reopen.

**Comment by Schnuggs** [comment] 2018-03-15 13:56
Well, now I'm running into a new build issue now:
`libettercap.so.0.0.0: undefined reference to 'GeoIP_cleanup'`
`collect2: error: ld returned 1 exit status`
`src/CMakeFiles/ettercap.dir/build.make:146: recipe for target 'src/ettercap' failed`
`make[2]: *** [src/ettercap] Error 1`
`CMakeFiles/Makefile2:287: recipe for target 'src/CMakeFiles/ettercap.dir/all' failed`
`make[1]: *** [src/CMakeFiles/ettercap.dir/all] Error 2`
`Makefile:127: recipe for target 'all' failed`
`make: *** [all] Error 2`

[Here is a screenshot.](https://imgur.com/a/dWUBL)

Any idea why this is happening?

**Comment by sgeto** [comment] 2018-03-18 13:59
Do `apt-get install libgeoip-dev`

GeoIP is optional. So you could alternatively disable it instead.

**Comment by koeppea** [comment] 2018-04-29 16:58
@sgeto Shouldn't this not occur since dcf8c6268e277d189187b991a486319e42bf8b98?

**Comment by koeppea** [comment] 2018-04-29 16:59
Closing as duplicate of #884

**Closed by koeppea** 2018-04-29 16:59 UTC
