### ISSUE TITLE
o5logon improvements?

### ISSUE THREAD

**Issue by LocutusOfBorg** [Ettercap/ettercap#842] opened 2017-10-13 17:42 UTC
(from the mail list)
I'm working with enhancements to the o5logon dissector. It collects
various packets where some of the data is optional so might not be seen
at all. In that case, I need to print the partial data we did collect.
While writing this (talk to the duck) I realized I can add trivial logic
to detect a TCP tear-down and implement it for that case.

However, I'd also want some kind of "catch EOF" functionality (callback,
macro, whatever) so any remaining sessions [that have enough data] can
be printed on EOF or end-of-sniff - a bit like atexit() if you wish.
That'd also mean a need for something like dissect_getnext() to iterate
over the sessions that remains.

Or put another way: I have this function:
```
FUNC_DECODER(dissector_o5logon)
{
      (...)
      dissect_create_session(&s, PACKET, DISSECT_CODE(dissector_o5logon));
      (...)
      if (condition) {
          dissect_wipe_session(PACKET, DISSECT_CODE(dissector_o5logon));
      }
}
```

I reckon I'd need something like this too:

```
FUNC_DECODER_EOF(dissector_o5logon)
{
      /* iterate through remaining sessions and process them */
      while (dissect_get_next_session(&s)) {
          (...)
          dissect_wipe_session_from_ptr(&s);
      }
}
```
Is this possible to achieve somehow already?

**Comment by koeppea** [comment] 2017-10-13 18:06
I think it's a bit hard w/o further background. AFAIK O5Logon is the Oracle SQL*net logon protocol. Maybe capture files that would demonstrate the behaviour.

**Comment by magnumripper** [comment] 2017-10-14 00:02
It's not limited to o5logon at all, so the issue name could be eg. "End-of-sniff event".

For example, it could be used in WPA sniffing as well. It goes like this: WPA handshakes are four way, let's call them M1..M4.
* If you get M1 and M2 you have enough data to crack whatever password the client used to authenticate with the AP (correct or not).
* If you also get M3, you also know that it was a **correct** password that the AP accepted.

So we could build a dissector that records M1, M2 and M3 packets. As soon as we see an M3 packet, we output a crackable hash. But when the sniff ends (end of sniff, end of pcap, end of file) you may still have some M1/M2 that never got a M3. They are still usable - so the stuff I wrote above could be used to iterate through them and output them too before quitting.

**Comment by magnumripper** [comment] 2017-10-14 00:08
BTW the o5logon stuff was merged in #742 already. The current work-around is we sometimes output dupe/irrelevant data.

**Comment by magnumripper** [comment] 2017-10-14 00:09
Oh, and I see now we already have #741 for this very issue. So this is a dupe!

**Comment by koeppea** [comment] 2017-10-14 07:40
> Oh, and I see now we already have #741 for this very issue. So this is a dupe!

Thanks for the hint @magnumripper 
Closing this issue as a duplicate of #741

**Closed by koeppea** 2017-10-14 07:40 UTC
