### ISSUE TITLE
Failed to open file “/root/.config/gtk-3.0/servers”: Permission denied in Kali 2020

### ISSUE THREAD

**Issue by jacknaguib** [Ettercap/ettercap#1081] opened 2020-10-26 20:13 UTC
kali@kali:~$ uname -r
5.8.0-kali2-amd64
kali@kali:~$ uname -r
5.8.0-kali2-amd64

kali@kali:~$ sudo su
[sudo] password for kali: 
root@kali:/home/kali# ettercap -G

ettercap 0.8.3.1 copyright 2001-2020 Ettercap Development Team

(ettercap:1321): Gtk-CRITICAL **: 16:01:58.436: Unable to create user data directory '/root/.local/share' for storing the recently used files list: Not a directory

(ettercap:1321): Gtk-WARNING **: 16:01:58.482: Unable to open server bookmarks: Failed to open file “/root/.config/gtk-3.0/servers”: Permission denied

Also, ARP poisoning victims with MITM attack, but not capturing Telnet communication. Not sure if that is related to the errors I listed above

Host 10.0.2.5 added to TARGET1         ----------> Windows Putty client connecting to Telnet server on 23 on Metasploitable server
Host 10.0.2.7 added to TARGET2       ----------> Metasploitable system running Telnet server

ARP poisoning victims:

 GROUP 1 : 10.0.2.5 08:00:27:E5:78:8A

 GROUP 2 : 10.0.2.7 08:00:27:1B:5F:1C

**Comment by koeppea** [comment] 2020-10-28 19:42
I reproduce the issue after I upgrade my Kali VM.
I can confirm the messages, however this is something implicitely triggered in the Gtk library.
Since Ettercap by default drops it's privileges to nobody (UID 65534), it's regardless if ettercap has been started as root or with sudo. It's dropping it's privileges explicitely for security reasons.

This means as well that you have in this case to choose a location to store the logfile where everybody has write access like e.g. /tmp. The Gtk messages itself have no functional impact on Ettercap.

If you are too annoyed by these messages, you can set ec_euid and ec_eguid to 0, to run ettercap with root privileges. This way  the Gtk messages do not appear.

Since the messages have no functional impact and are clearly related to the privilege drop which has security reasons, I'll close this issue.

Regarding your other topic, I'd like to ask you to open a dedicated issue discussing that separately.

**Closed by koeppea** 2020-10-28 19:42 UTC
