### ISSUE TITLE
Weird ip adresses

### ISSUE THREAD

**Issue by Merlinistisch** [Ettercap/ettercap#1218] opened 2023-02-22 22:59 UTC
The ip adresses that i get are 10.2.2 10.2.3 10.2.4
Mac adresses: 52:54:00:12:35:02, 52:54:00:12:35:03, 52:54:00:12:35:04, i booted up ettercap through the root terminal, i used eth0  clicked accept, clicked on scan for hosts, Lua: no scripts were specified, not starting up! Was something that was shown in the text box, i didn't specify the netmask, the textbox also said: Ettercap might not work correctly. /proc/sys/net/ipv6/conf/eth0/use_tempaddr is not set to 0.
Privileges dropped to EUID 0 EGID 0...

**Comment by LocutusOfBorg** [comment] 2023-02-23 11:50
so what is the issue?

**Comment by LocutusOfBorg** [comment] 2023-02-23 11:51
what does ifconfig report?

**Comment by koeppea** [comment] 2023-02-24 00:00
Could you please run the following command on CLI:
```
sudo ettercap -Tqslq
```
and paste the ouput here?

**Comment by Merlinistisch** [comment] 2023-02-24 02:32
> Could you please run the following command on CLI:
> 
> ```
> sudo ettercap -Tqslq
> ```
> 
> and paste the ouput here?

the output is : 
ettercap 0.8.3.1 copyright 2001-2020 Ettercap Development Team

Listening on:
  eth0 -> 08:00:27:02:4B:E7
          10.0.2.15/255.255.255.0
          fe80::a00:27ff:fe02:4be7/64

SSL dissection needs a valid 'redir_command_on' script in the etter.conf file
Ettercap might not work correctly. /proc/sys/net/ipv6/conf/eth0/use_tempaddr is not set to 0.
Privileges dropped to EUID 65534 EGID 65534...

  34 plugins
  42 protocol dissectors
  57 ports monitored
28230 mac vendor fingerprint
1766 tcp OS fingerprint
2182 known services
Lua: no scripts were specified, not starting up!

Randomizing 255 hosts for scanning...
Scanning the whole netmask for 255 hosts...
* |==================================================>| 100.00 %

3 hosts added to the hosts list...
Starting Unified sniffing...


Text only Interface activated...
Hit 'h' for inline help



Hosts list:

1)      10.0.2.2        52:54:00:12:35:02
2)      10.0.2.3        52:54:00:12:35:03
3)      10.0.2.4        52:54:00:12:35:04


Closing text interface...


Terminating ettercap...
Lua cleanup complete!
Unified sniffing was stopped.

**Comment by koeppea** [comment] 2023-02-24 05:47
Thanks. But I can’t see what’s weird with these IP addresses or MAC addresses.

To me also everything is looking ok. The warning with the temp_addr only relates to IPv6.

**Comment by Merlinistisch** [comment] 2023-02-24 11:38
I know that the ip adresses of my phone, the virtual machine and my pc aren't listed.

**Comment by koeppea** [comment] 2023-02-26 18:58
Can you please re-run the command with the `-w /tmp/packets.pcap` and provide the file _/tmp/packets.pcap_?

**Comment by Merlinistisch** [comment] 2023-03-09 10:21
Iit says: -w /tmp/packets.pcap

**Comment by koeppea** [comment] 2023-03-09 22:04
Well or should not say anything different but have a file packet.pcap in /tmp directory.

**Comment by Mnanuk** [comment] 2023-03-21 17:47
I have the same problem 
did you found how to fix it guys ?

**Comment by koeppea** [comment] 2023-03-22 18:52
I cannot reproduce it. Therefore I asked to re-run incl. the `-w /tmp/packets.pcap`.

**Comment by Mnanuk** [comment] 2023-03-25 15:00
okaaay I found the problem 
we were on NAT mode in our VM 
switch to the bridge mode that allow your VM to be like a physical computer and have his own IP adress 

go to the setting of your VM then networks or something like that and switch from nat to bridge

**Comment by koeppea** [comment] 2023-03-25 20:36
Thanks for sharing your finding. Closing the issue then.

**Closed by koeppea** 2023-03-25 20:36 UTC
