### ISSUE TITLE
Some errors on mac os x with homebrew/macports

### ISSUE THREAD

**Issue by Eren4363** [Ettercap/ettercap#832] opened 2017-09-21 18:53 UTC
I installed ettercap with gtk+ using macports and I got this issue with sudo -E ettercap -G

(<unknown>:2289): Gtk-CRITICAL **: gtk_image_get_pixbuf: assertion 'image->storage_type == GTK_IMAGE_PIXBUF || image->storage_type == GTK_IMAGE_EMPTY' failed

The version on macports had more issues such as the curses gui not working properly when scanning for hosts (running with sudo). So I uninstalled macports and its packages and used homebrew. This time i get the same error but only on my macbook pro, i get this too

ettercap[2289:75907] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 

I think it's because of the retina screen. 

These errors doesn't affect functionality, I can still sniff and do attacks but they are worrying.

**Comment by koeppea** [comment] 2017-09-25 09:02
It's not harmful. 
The definition of the window icon fails, most probably due to some path issues. 
This week I have a Mac book available (just posting a Mac -related video on our channel). 
I'll take a look into it.

**Comment by sgeto** [comment] 2017-09-26 22:08
> just posting a Mac -related video on our channel

ettercap's channel?

**Comment by koeppea** [comment] 2017-09-27 07:20
> ettercap's channel?

yes: https://www.youtube.com/channel/UCVYP1AeH9G1E1rtllwxLEQA/videos

**Comment by koeppea** [comment] 2017-09-27 08:12
The problem is due to a implicit behavior of the `gtk_image_new_from_file()` function.

> If the file isn’t found or can’t be loaded, the resulting GtkImage will display a “broken image” icon. 

It implicitly creates a _GdkPixbuf_ from the file and then creates a _GtkImage_. The first step fails, which leads to the above quote behavior. 
Now the call of `gtk_image_get_pixbuf()` is being watched by the assertion mentioned in the error message, because the storage type of the "_broken image_" icon is neither of the both types, but a **GTK_IMAGE_STOCK**.

The reason why the _GdkPixbuf_ cannot be created lies in the missing loader for SVG of the **libpixbuf** library. 

I cannot yet tell, if this is just to to the Homebrew formula or due to a incompatibility issue when porting **gtk+** on MacOS.

**Comment by koeppea** [comment] 2017-10-10 18:46
@Eren4363 closing this, since the warning comes from the *gtk+* port, not Ettercap and is not having an tangible effect on Ettercap.

Feel free to reopen in case you don't comply.

**Closed by koeppea** 2017-10-10 18:46 UTC
