### ISSUE TITLE
(DNS SPOOFING) Problem with redirect real website into fake website use https 

### ISSUE THREAD

**Issue by ricko2991** [Ettercap/ettercap#1082] opened 2020-10-31 11:22 UTC
Hi, I have previously made a certificate, maybe the explanation can be seen at this link: https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-16-04

Yes, from this link I managed to open https but using my ip address. But when I open a website that should be redirected to my site (eg: www.facebook.com), I get an error like this:
![Screenshot (205)](https://user-images.githubusercontent.com/67855001/97777660-b0d4e800-1bac-11eb-974b-8ae434a1a9d7.png)

I also added a `certificate Manager` exception in firefox so that this site can be trusted, but it doesn't work, the error is still like the one above.

To check if the website allow to acces i open it on client terminal use this command:
curl -v https://www.facebook.com. The output is:
![Screenshot (207)](https://user-images.githubusercontent.com/67855001/97777791-859ec880-1bad-11eb-826f-d0bb8da6537e.png)

I've tried to read a lot of articles but I can't find the answer, so maybe here the problem is an untrusted certificate, I don't know how to make it trustworthy anymore in apache2, is there any idea for this problem?

**Comment by koeppea** [comment] 2020-10-31 14:21
All the error messages in the above outputs, absolute clearly and precisely explain what the issue is.
Your client / web browser does not trust the server certificate because it can not be validated against a trusted CA certificate. See our [Wiki article about HSTS](https://github.com/Ettercap/ettercap/wiki/HTTPS-and-HSTS).

Firefox has it's own CA certificate trust store. If you want to add a exception for a server certificate, you have to add it to the section section of Firefox. Otherwise, you have to create a CA certificate, import it into the CA certificate store and sign your server certificate using this CA certificate.

Other browsers leverage the OS certificate trust store, but this differs depending on the OS or even distribution.
However teaching you on this, goes too far for commenting this issue for Ettercap.

I recommend you, to begin faking a non-HSTS protected website. 

Since the curl output shows that **dns_spoof** plugin does work and returns the IP of the fake Webserver, I'm closing this case, as it's not an issue with Ettercap at all.

**Closed by koeppea** 2020-10-31 14:21 UTC
