### ISSUE TITLE
Spoofed certificate cannot be generated on the fly

### ISSUE THREAD

**Issue by rennhard** [Ettercap/ettercap#923] opened 2019-01-30 12:36 UTC
I've been using ettercap in classroom at a university for years and I understand the tool quite well. I've just updated the Ubuntu and Kali systems (I'm running them in a VM) I'm using for this to the latest version and as a result of this, SSL spoofing no longer works. In particular, it seems ettercap has problems to generate the spoofed certificate on the fly.

When I'm specifying certificate and private key on the CL, it works without problems:

ettercap -T -M ARP /192.168.57.247/ /192.168.57.248/ --certificate cert.pem --private-key key.pem 

However, when doing the same without specifying certificate and private key, it doesn't work. Details can be observed from the attached Wireshark trace:

- Packet 4 shows the Client Hello from the client received by ettercap
- From packet 5 to 17, ettercap establishes the TCP connection and the TLS handshake with the server, without any problems
- In packet 18, ettercap sends a TLS alert to the client (instead of the Server Hello that is expected)

I strongly suspect there's a problem with generating the spoofed certificate because - I guess - this is what happens after ettercap has completed the TLS handshake with the server. This is undermined by the fact that everything works fine when specifying certificate and private key on the CL. 

BTW: etter.conf is configured correctly. Also, I tested this using real browsers and servers and also with openssl using s_server and s_client. Furthermore, this has been confirmed both with the latest downloadable version (0.8.2) and also when building ettercap from the source code.

Is this a bug or am I missing something?

Thanks for any help!

![screenshot 2019-01-30 at 13 25 38 2](https://user-images.githubusercontent.com/19332950/51981484-78622080-2493-11e9-96e9-ac87e096ba25.png)

**Comment by koeppea** [comment] 2019-01-30 13:46
Thanks for the high quality issue reporting. I’ll have a close look at it as soon as possible.

However since there have been ton of bug fixes in the latest Master on GitHub, could you please try to reproduce using a built from the latest code in the meantime?

You’re better off launching a fresh VM for that.

**Comment by rennhard** [comment] 2019-01-30 17:45
Thanks for the quick response.

I've already been using the latest code.

But I found out something else: So far, I've been using ettercap on a Kali system (which I updated to the latest version and where I used the latest ettercap code). There, I got the erroneous behavior as above. But now I tested ettercap (latest code) on an updated Ubuntu system - there it works flawlessly.

I guess this may have something to do with a dependency used by ettercap? Maybe one that's used to create certificates? Is there any information I can provide you with?

**Comment by koeppea** [comment] 2019-01-30 19:32
BTW: Maybe you also want to have a look at / test my just issued pull-request which I just found in my _stash_: #924

**Comment by koeppea** [comment] 2019-01-31 19:08
The build error came up first time when OpenSSL 1.1  was introduced. I'll have a closer look at that. Thanks for the tests and heads up.
Do I get it right, that we can close this issue then?

**Comment by rennhard** [comment] 2019-01-31 19:12
Can be closed. Thanks for the very timely responses!

**Comment by koeppea** [comment] 2019-01-31 19:32
Closing then. Following up independently in the scope of #924 .

**Closed** 2019-01-31 19:32 UTC
