### ISSUE TITLE
ettercap 0.8.3.1 issue with null char \x00?

### ISSUE THREAD

**Issue by graythang** [Ettercap/ettercap#1086] opened 2020-11-11 03:05 UTC
Is there a known issue with use of the null hex code in filters?  It appears to be truncating the string whenever a \x00 is encountered.  Here is what Im seeing:

Test case using \x00 in string (second test case below is w/o the null in the string)

************ test case 1 using \x00*************
 >etterfilter myfilter 
     where myfilter contains:

if (ip.proto == TCP && tcp.dst == 1433) {
        msg("Found Our target Traffic");
        if (search(DATA.data,"\x61\x00\x61\x00\x61\x00\x61\x00\x74\x00\x65\x00\x73\x00\x74\x00\x31\x00\x31")) {
        msg("Found Our target String");
        replace("\x61\x00\x61\x00\x61\x00\x61\x00\x74\x00\x65\x00\x73\x00\x74\x00\x31\x00\x31\x00","\x62\x00\x62\x00\x62\x00\x62\x00\x74\x00\x65\x00\x73\x00\x74\x00\x31\x00\x31\x00");
        msg("...and replaced it:)");
        }
}

************
etterfilter -t filter.ef   results in: 
etterfilter 0.8.3.1 copyright 2001-2020 Ettercap Development Team

Content filters loaded from filter.ef...
Disassebling "filter.ef" content...

0000: TEST level 3, offset 9, size 1, == 6 [0x6]
0001: JUMP IF FALSE to 0010
0002: TEST level 4, offset 2, size 2, == 1433 [0x599]
0003: JUMP IF FALSE to 0010
0004: MSG "Found Our target Traffic"
0005: SEARCH level 5, string "a"
0006: JUMP IF FALSE to 0010
0007: MSG "Found Our target String"
0008: REPLACE "a" --> "b"
0009: MSG "...and replaced it:)"

 10 instructions decoded.

***************** test case 2 no \x00 string *********************
Second test case omitting "\x00" from filter string
 >etterfilter myfilter2 
     where myfilter2 contains:

if (ip.proto == TCP && tcp.dst == 1433) {
        msg("Found Our target Traffic");
        if (search(DATA.data,"\x61\x61\x61\x61\x74\x65\x73\x74\x31\x31")) {
        msg("Found Our target String");
        replace("\x61\x61\x61\x61\x74\x65\x73\x74\x31\x31","\x62\x62\x62\x62\x74\x65\x73\x74\x31\x31");
        msg("...and replaced it:)");
        }
}

etterfilter -t on filter.ef results in
etterfilter 0.8.3.1 copyright 2001-2020 Ettercap Development Team

Content filters loaded from filter.ef...
Disassebling "filter.ef" content...

0000: TEST level 3, offset 9, size 1, == 6 [0x6]
0001: JUMP IF FALSE to 0010
0002: TEST level 4, offset 2, size 2, == 1433 [0x599]
0003: JUMP IF FALSE to 0010
0004: MSG "Found Our target Traffic"
0005: SEARCH level 5, string "aaaatest11"
0006: JUMP IF FALSE to 0010
0007: MSG "Found Our target String"
0008: REPLACE "aaaatest11" --> "bbbbtest11"
0009: MSG "...and replaced it:)"

 10 instructions decoded.

**Comment by koeppea** [comment] 2020-11-11 20:07
Closing as duplicate of #1087

**Closed by koeppea** 2020-11-11 20:07 UTC
